### ISSUE TITLE
Old `v1` tag

### ISSUE THREAD

**Issue by Rubilmax** [foundry-rs/foundry-toolchain#56]
Either:

- point v1.2.0 README to use `foundry-rs/foundry-toolchain@v1.2.0`

OR

- update tag `v1` to point to `v1.2.0`

Because currently, `foundry-rs/foundry-toolchain@v1` points to an old version without built-in cache!

**Comment by QGarchery** [comment]
I think that this is fixed now, as the v1 tag points to v1.1.1. Also this is documented in [this commit](https://github.com/foundry-rs/foundry-toolchain/commit/66af43d8beaeedafe9eddae6139546324e293b04)

**Comment by Rubilmax** [comment]
Right, but the latest version is `v1.2.0` not `v1.1.1` so I agree it's an improvement already but it's still not up to date 😊

**Comment by zerosnacks** [comment]
The `v1` tag has now been updated to `v1.3.0`, our latest release
